version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: tslib
    versions:
    - 2.0.3
    - 2.1.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.29.0
  - dependency-name: "@types/react-redux"
    versions:
    - 7.1.11
